<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>isi data Due</name>
   <tag></tag>
   <elementGuidId>141224ea-1037-4c94-8e6b-248f6e497d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table1']/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a15a24c9-d544-4e85-a7eb-36cd5d0327c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$50.00</value>
      <webElementGuid>2685af90-847e-4fae-ba7a-ab8616a516db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table1&quot;)/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>d9ce4f02-8448-492f-bafc-385691c914fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table1']/tbody/tr/td[4]</value>
      <webElementGuid>a0001822-8d0d-4e08-8d9e-e4d200b694c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jsmith@gmail.com'])[1]/following::td[1]</value>
      <webElementGuid>ceac8799-7613-4542-8ef8-2c60a8598e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John'])[1]/following::td[2]</value>
      <webElementGuid>ebb3f735-1dd4-4f6c-8f5f-4aa3eb9a7fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='http://www.jsmith.com'])[1]/preceding::td[1]</value>
      <webElementGuid>e06a960e-a3eb-478c-b730-b565bf6cb02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='edit'])[1]/preceding::td[2]</value>
      <webElementGuid>9b02adf3-86eb-45e7-9d75-40302819e78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$50.00']/parent::*</value>
      <webElementGuid>02f46694-599e-4021-b3e2-f4c21bfd5ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>70151cb7-37b5-44bf-bc89-c72e01c20568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$50.00' or . = '$50.00')]</value>
      <webElementGuid>1471f4e3-0d3b-4ee5-af14-9998042ba735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
