<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pending</name>
   <tag></tag>
   <elementGuidId>daa19f4c-e928-426b-9352-671f31c2d8e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.open > ul.dropdown-menu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[1]/section[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr/td[8]/center/div/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d53d1f5-902a-41e9-9ef4-e51905a4d168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Yakin Ubah status pesanan jadi Pending?')</value>
      <webElementGuid>d86a5419-6056-453b-bb18-8ec5722d459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=624&amp;status=0</value>
      <webElementGuid>8ed3e864-ee43-4d95-ba04-3be671840000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>a17df95a-c851-42f0-99a1-d3e33962c78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[8]/center[1]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>261e50e5-f7ff-4fd3-927e-9ee768777f91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Pending?')&quot;])[2]</value>
      <webElementGuid>06583ce3-9a17-4fac-a620-8bc064a6837d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr[2]/td[8]/center/div/ul/li/a</value>
      <webElementGuid>5da63bd3-6162-49d1-a99a-461542887aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pending')])[2]</value>
      <webElementGuid>76d7feb9-2c62-493c-bb45-2d422844a92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 6,299 (1 Produk)'])[1]/following::a[1]</value>
      <webElementGuid>f8436e15-181d-4ae8-9f0b-f81f4b463dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[2]/following::a[1]</value>
      <webElementGuid>603cec31-7836-41d4-a44e-5e00d9b349b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[2]/preceding::a[1]</value>
      <webElementGuid>6a4f9ad1-1a78-48e8-9421-b42133f4559f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi'])[2]/preceding::a[2]</value>
      <webElementGuid>149e5057-6b51-4d0d-aa88-83c8ce1f0e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=624&amp;status=0')]</value>
      <webElementGuid>d2710ecd-c205-408f-a8c9-e7cb6cca0432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/center/div/ul/li/a</value>
      <webElementGuid>2a8a7cae-8071-4dc8-80e7-cd6f72b8319a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=624&amp;status=0' and (text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>9bcd4067-9d13-417c-a398-ccbf887320bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
