<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Showing 1 to 10 of 206 entries</name>
   <tag></tag>
   <elementGuidId>6a67b634-965d-4f59-a8ca-2526e63ef08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#example1_info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='example1_info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c0f43fc-53f6-4776-947c-3ccd4e8b500a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_info</value>
      <webElementGuid>8e0c7b86-301c-415c-9423-db89deaf08d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>example1_info</value>
      <webElementGuid>c09f4ed4-0954-4223-a307-d403bfe3009d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>d6dcc85e-c59e-4ab5-9eb7-ae2f82fdfd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>da8e648f-e75b-4cfb-8e06-b83b11dd2b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 to 10 of 206 entries</value>
      <webElementGuid>8ffe4921-fe6a-42f1-90e7-ac687af5d521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1_info&quot;)</value>
      <webElementGuid>cfcef05f-ad24-4d4d-b865-acb16c811eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='example1_info']</value>
      <webElementGuid>3e9288d2-6765-4bfb-9c92-2faf7876a7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='example1_wrapper']/div[3]/div/div</value>
      <webElementGuid>c71839bf-5bd0-45e2-8070-dd286729578a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal/Hapus'])[9]/following::div[3]</value>
      <webElementGuid>f0ff701a-d82a-4a38-9d1f-17063c647d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[11]/following::div[3]</value>
      <webElementGuid>f29fe203-1423-48be-8863-68b06d72ca6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace PRO'])[1]/preceding::div[4]</value>
      <webElementGuid>ef8fee01-508e-4ace-b982-e97346ff1b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showing 1 to 10 of 206 entries']/parent::*</value>
      <webElementGuid>3577f602-8ec0-402f-a164-aa72be170e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>eaf9c76d-5c36-4d26-a5c8-257b32d5d7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'example1_info' and (text() = 'Showing 1 to 10 of 206 entries' or . = 'Showing 1 to 10 of 206 entries')]</value>
      <webElementGuid>8dfcc04b-7533-4fcd-8683-7921cd18c72d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
