<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hasil edit no_hp</name>
   <tag></tag>
   <elementGuidId>c0b0dd74-9c01-4a3a-94d8-c802ac4ca1f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profile']/div/table/tbody/tr[6]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(6) > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cd057da7-00ae-47c0-a998-196343852352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>081212121212</value>
      <webElementGuid>49682b72-1d17-4951-8367-a9cb936ced84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile&quot;)/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table table-condensed table-bordered&quot;]/tbody[1]/tr[6]/td[1]</value>
      <webElementGuid>ffbf8379-6097-4810-80a1-bbc32026c257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/table/tbody/tr[6]/td</value>
      <webElementGuid>4da658ce-5d5d-4115-86ef-e1ef661a9f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Hp'])[1]/following::td[1]</value>
      <webElementGuid>06c09806-b48b-4c20-96ae-51173c7f14ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='udin123@gmail.com'])[1]/following::td[1]</value>
      <webElementGuid>18164d96-2c0c-4db4-8acb-1eae29170a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[1]/preceding::td[1]</value>
      <webElementGuid>af086144-b1f1-4a76-9a66-9210c30879e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki-laki'])[1]/preceding::td[1]</value>
      <webElementGuid>63607094-9a6b-402e-8d50-07fefadf5336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='081212121212']/parent::*</value>
      <webElementGuid>3ffedf50-76f8-405e-88f1-01ca9831bc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td</value>
      <webElementGuid>8d89fd29-0e50-4ddb-b38b-e4e57817525e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '081212121212' or . = '081212121212')]</value>
      <webElementGuid>77ad4fb7-ebe3-49a7-aab8-6462be19bf33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
