<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tittle nomor transaksi</name>
   <tag></tag>
   <elementGuidId>6805a728-7885-46e8-a9bc-dfa50575fec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.breadcrumb > li:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ed263545-b831-4f31-b3e6-994eec098af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRX60.20230913165049</value>
      <webElementGuid>69b99f0f-f021-45f9-aa1e-cfcc66cb0eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-breadcrumb&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;breadcrumb&quot;]/li[3]</value>
      <webElementGuid>13a3c5ce-4dc7-43b0-8362-f354b3e1bfae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking'])[1]/following::li[1]</value>
      <webElementGuid>1f76cbb3-240d-4c09-a677-c7b880111343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::li[2]</value>
      <webElementGuid>5f9eb106-3c84-4c0e-a7a0-a4c8a95d354e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Invoice'])[1]/preceding::li[1]</value>
      <webElementGuid>50214fe0-e8c0-4d61-908f-bcde6e444600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRX60.20230913165049'])[2]/preceding::li[1]</value>
      <webElementGuid>c1bc0255-064c-44d2-b425-647ccc4f8d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRX60.20230913165049']/parent::*</value>
      <webElementGuid>53eb530d-be7d-4850-b7f8-da3b33baaf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/ul/li[3]</value>
      <webElementGuid>15c56db2-ee45-457a-9554-295357b94ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'TRX60.20230913165049' or . = 'TRX60.20230913165049')]</value>
      <webElementGuid>d3459887-0aeb-4428-8a8c-42c358d3ad89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
