<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ter-verifikasi</name>
   <tag></tag>
   <elementGuidId>374ff730-5fb6-4924-82f7-4c205eee4f9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myModalDetail']/div/div/div[2]/div/dl/dd[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5de87a9b-67ec-4d22-815a-7b595dc3d636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ter-verifikasi</value>
      <webElementGuid>907dee7f-20a1-4481-bc7a-dd7ecaa40278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;active&quot;]/body[@class=&quot;skin-black-light sidebar-mini pace-running active modal-open pace-running&quot;]/div[@class=&quot;wrapper active&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;box&quot;]/div[@id=&quot;myModalDetail&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;content-body&quot;]/dl[@class=&quot;dl-horizontal&quot;]/dd[7]/span[1]</value>
      <webElementGuid>4de607be-7403-41c2-b4f4-2f01409cc21e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalDetail']/div/div/div[2]/div/dl/dd[7]/span</value>
      <webElementGuid>39b9a90e-fc6c-42ef-8ce3-94bb79732a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::span[1]</value>
      <webElementGuid>04afae1c-598f-48ab-a1c0-d1b04525b2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak ada file dilampirkan...'])[1]/following::span[1]</value>
      <webElementGuid>d048a6fa-345c-4945-9e7d-9ce2d327abf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace PRO'])[1]/preceding::span[1]</value>
      <webElementGuid>4ac38c47-0b4c-451a-91a1-5985081b2e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ter-verifikasi']/parent::*</value>
      <webElementGuid>4b287186-d543-4c3c-a981-b5e4dfbf40e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[7]/span</value>
      <webElementGuid>3daa04ce-f42e-4efc-8fc1-498ea810eab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ter-verifikasi' or . = 'Ter-verifikasi')]</value>
      <webElementGuid>a4a63a65-2aaa-4faf-aa43-8b88b2a9c1a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
