<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose files_uploadFile</name>
   <tag></tag>
   <elementGuidId>e89ba241-5581-4fbd-986b-d633e1b9cf9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'file' and @name = 'uploadFile[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ajax-upload-id-1694165577064</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ajax-upload-id-1695781657717&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22aa8d25-c7fb-498b-87bf-ece2dc156b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e40c9e8d-4cff-475b-af54-b3e941a50d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ajax-upload-id-1694165577064</value>
      <webElementGuid>acd72e14-13ca-47b8-9335-b0fc412ac130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uploadFile[]</value>
      <webElementGuid>512f842f-8727-42c6-8461-57a4d7a25982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajax-upload-id-1694165577064&quot;)</value>
      <webElementGuid>91427411-4c95-43ec-8529-510b3adebfcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ajax-upload-id-1694165577064']</value>
      <webElementGuid>3927fdf8-774a-4bfa-8b5d-66c3010bc330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/input</value>
      <webElementGuid>90943b12-3dc1-4c6d-8152-1ca0d01225ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ajax-upload-id-1694165577064' and @name = 'uploadFile[]']</value>
      <webElementGuid>3e1e6261-13ae-4e4b-afbe-5413ac296053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
