<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Men Singelete - Baju Dalam Menarik</name>
   <tag></tag>
   <elementGuidId>313eeac2-6a60-4300-ae03-a121f218af85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-1']/div/div/div[3]/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dad3a71a-a83a-4d7f-9320-54b597a5f12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-product__title</value>
      <webElementGuid>23b9a6fe-d1f9-4a9b-addb-fe57987ce56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/produk/detail/men-singelete--baju-dalam-menarik</value>
      <webElementGuid>5fcdab42-254d-4248-afa1-096bdaeb8991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men Singelete - Baju Dalam Menarik</value>
      <webElementGuid>04d98cd3-1f8c-4c0c-b598-17b4a0937cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)/div[@class=&quot;ps-shopping-product&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-md-4 col-sm-6 col-6&quot;]/div[@class=&quot;ps-product&quot;]/div[@class=&quot;ps-product__container&quot;]/div[@class=&quot;ps-product__content hover&quot;]/a[@class=&quot;ps-product__title&quot;]</value>
      <webElementGuid>20b0362a-8794-467b-a41c-0255131a73ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-1']/div/div/div[3]/div/div[2]/div[2]/a</value>
      <webElementGuid>0924d69d-016a-4a5e-b934-7ce68eed8a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Men Singelete - Baju Dalam Menarik')])[2]</value>
      <webElementGuid>ce6306de-1de7-46ed-942a-b60bf9016abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Singelete - Baju Dalam Menarik'])[1]/following::a[1]</value>
      <webElementGuid>e5ff81df-e50f-42cd-b48c-f27ecf77d3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Umar Lapakers'])[1]/following::a[2]</value>
      <webElementGuid>cbd587e1-b9b4-4f5d-b8b0-04537dd566a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarii Sentral Java'])[1]/preceding::a[5]</value>
      <webElementGuid>6d16bb4f-9b9c-4bc4-a017-cdf082d6e2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koku Black Cotton Sesnsation Gamis TY-,..'])[1]/preceding::a[6]</value>
      <webElementGuid>d3982c25-f206-43a8-96eb-66a3a85857ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://10.9.2.63/ecommerce/produk/detail/men-singelete--baju-dalam-menarik')])[3]</value>
      <webElementGuid>17e47b5e-4d03-44b3-9857-51edd08eb753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/a</value>
      <webElementGuid>aa4ad709-aff5-4f64-a557-a6155c2bc425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/produk/detail/men-singelete--baju-dalam-menarik' and (text() = 'Men Singelete - Baju Dalam Menarik' or . = 'Men Singelete - Baju Dalam Menarik')]</value>
      <webElementGuid>65fe33e2-91b4-4fd3-aa6d-8579abbf2f2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
