<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>beli kebarang</name>
   <tag></tag>
   <elementGuidId>cd15346a-9598-4c95-b94c-734d1a1c7e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.ps-product__actions.produk-40 > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-1']/div/div/div[3]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a32c29fa-843c-4f1d-b8ee-06b68e7ef5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/produk/detail/men-singelete--baju-dalam-menarik</value>
      <webElementGuid>4c922f72-bcff-4cd9-9f6d-4a9d137dade4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>4c9159fb-7ad3-4608-a1bc-68645ba53c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>e246dbda-e525-4573-ae71-c97e50eabe68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Read More</value>
      <webElementGuid>ea63a030-0c00-4a73-b738-2cee1a181826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip552889</value>
      <webElementGuid>03e2464a-27f0-46cf-9ad9-30c7e940feae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)/div[@class=&quot;ps-shopping-product&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-md-4 col-sm-6 col-6&quot;]/div[@class=&quot;ps-product&quot;]/div[@class=&quot;ps-product__thumbnail&quot;]/ul[@class=&quot;ps-product__actions produk-40&quot;]/li[1]/a[1]</value>
      <webElementGuid>25d50a9b-cd75-49ce-9e50-91131162004f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-1']/div/div/div[3]/div/div/ul/li/a</value>
      <webElementGuid>5eab7eb3-a5b2-4ab1-8baa-ce9bfe830d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju Koko Kids 0 - 9 tahun'])[4]/following::a[2]</value>
      <webElementGuid>131609cb-ea81-4ba1-9df1-1c48dae2db5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju Koko Kids 0 - 9 tahun'])[3]/following::a[3]</value>
      <webElementGuid>4fb1b380-c804-4cfc-be14-6c6456300f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Umar Lapakers'])[1]/preceding::a[3]</value>
      <webElementGuid>5336874f-3793-4db4-ab08-caa43a5d278e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Singelete - Baju Dalam Menarik'])[1]/preceding::a[4]</value>
      <webElementGuid>39a9b6b1-7724-4aa0-a187-a49f9fda8180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/produk/detail/men-singelete--baju-dalam-menarik')]</value>
      <webElementGuid>c87ffc9b-447e-45ae-af1e-b1f822af08cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li/a</value>
      <webElementGuid>41091b0c-be4f-4932-a405-0d21eb3aae18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/produk/detail/men-singelete--baju-dalam-menarik']</value>
      <webElementGuid>6e759774-cda1-478d-8663-7042c375c46a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
