<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Mulai Belanja_icon-menu</name>
   <tag></tag>
   <elementGuidId>1a07bc57-76db-4408-abe9-ce42902cf7ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.navigation__left > div.menu--product-categories > div.menu__toggle > i.icon-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav/div/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9731c7f4-72a3-4f3b-972c-9718293e3fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-menu</value>
      <webElementGuid>54bf0372-26bd-46b7-9594-7d4082518f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/header[@class=&quot;header header--1&quot;]/nav[@class=&quot;navigation&quot;]/div[@class=&quot;ps-container&quot;]/div[@class=&quot;navigation__left&quot;]/div[@class=&quot;menu--product-categories&quot;]/div[@class=&quot;menu__toggle&quot;]/i[@class=&quot;icon-menu&quot;]</value>
      <webElementGuid>53504aab-2607-43ed-8b05-9463d1be0eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/div/i</value>
      <webElementGuid>c9445149-e53d-41d7-8c97-2984777454a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
