<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon keranjang</name>
   <tag></tag>
   <elementGuidId>32f5efc4-9bb2-455c-b8ad-ed2c465eab3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.header__extra > i.icon-bag2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0a0f3b3f-06b1-4fcc-bcac-bedbee7e9d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bag2</value>
      <webElementGuid>59008be3-55b5-4cf3-b986-930375b16c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/header[@class=&quot;header header--1&quot;]/div[@class=&quot;header__top&quot;]/div[@class=&quot;ps-container&quot;]/div[@class=&quot;header__right&quot;]/div[@class=&quot;header__actions&quot;]/div[@class=&quot;ps-cart--mini&quot;]/a[@class=&quot;header__extra&quot;]/i[@class=&quot;icon-bag2&quot;]</value>
      <webElementGuid>bb6fc6a6-95dd-4fb3-a068-db44a4f898e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/i</value>
      <webElementGuid>08150793-e0fc-48d8-a27c-c88246bfc23e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
