<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kendaraan Kurir</name>
   <tag></tag>
   <elementGuidId>232b8190-7ff0-42c3-adcd-fdeca98c59a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serv-99-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='serv-99-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6832b234-e32d-4161-bbfa-ae5af01de75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serv-99-2</value>
      <webElementGuid>de51cd73-8d18-4939-a93c-9731e8a885ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>klikongkir10('2','SOPIR','5000','5,000',this.id)</value>
      <webElementGuid>f5419aee-59c0-4121-a97c-747c763b2a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item clearall-kurir selected-ongkir10</value>
      <webElementGuid>03888428-0a86-4655-9a62-95490c6d42e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vixion R (BA 4665 LN) Rp. 5,000 / </value>
      <webElementGuid>9e00f053-e3cb-415a-86b9-13c13a2cfc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serv-99-2&quot;)</value>
      <webElementGuid>79195eb2-2cdf-4ac5-8b8d-426c21f54910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='serv-99-2']</value>
      <webElementGuid>e5effbab-f52c-45a0-8300-e64e5abeffd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_sopir_div1']/li</value>
      <webElementGuid>87682fd9-4615-4093-8968-888659f88504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim via COD (Bayar Di tempat)'])[1]/following::li[1]</value>
      <webElementGuid>3e191578-09e9-45dc-a58b-b4d04ec1dc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarii Sentral Java'])[2]/following::li[1]</value>
      <webElementGuid>81690ab5-17c1-4cb8-8d79-538f26c3cce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>aa52a1e0-a6b4-4113-92fc-298291d4b148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'serv-99-2' and (text() = 'Vixion R (BA 4665 LN) Rp. 5,000 / ' or . = 'Vixion R (BA 4665 LN) Rp. 5,000 / ')]</value>
      <webElementGuid>01c82f5f-18b0-49aa-8c19-bc0c3a0bec19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
