<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>metode pembayaran</name>
   <tag></tag>
   <elementGuidId>35948897-b146-42ba-976d-884fdaf03802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'metode' and @id = 'saldo' and @value = 'saldo']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saldo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saldo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>def2fe9b-7733-4205-946f-c075fb2ea9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f7163666-de65-40d9-a345-18707395237a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>metode</value>
      <webElementGuid>411e6593-cff4-4853-8f3d-c51e473f7b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>11979991-be19-408c-bc03-e067c8fe562c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>68526a29-13cb-48b4-af33-5b9c5c109905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saldo&quot;)</value>
      <webElementGuid>9cffd053-ea45-4d39-8f00-45fd36894454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saldo']</value>
      <webElementGuid>7e5572c7-9c1c-4e09-b14b-457ffcb1664c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>e2a860d3-ac25-401a-8789-a1b6ff6f49b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'metode' and @id = 'saldo']</value>
      <webElementGuid>efc10a8f-88e5-4fe0-9d4e-4a0e687e2f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
