<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select - Kirim via Kurir Lokal</name>
   <tag></tag>
   <elementGuidId>8a05658d-41a8-4708-96e8-3a8e5de3dd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list_sopir1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='list_sopir1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>04715482-ed6a-47ec-943e-859af0042d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini text-success</value>
      <webElementGuid>49911f15-182f-41aa-9a4b-f94c6b3e29f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_sopir1</value>
      <webElementGuid>a0976431-3ba4-4f9e-8074-14a9cf730148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_sopir1</value>
      <webElementGuid>a328ad77-80c4-441e-86bd-766865e77a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                              - Kirim via Kurir Lokal -Roda 2Roda 4</value>
      <webElementGuid>6f908c68-e828-4ca2-915a-74e602bd6ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_sopir1&quot;)</value>
      <webElementGuid>88d57851-83d6-4cb9-8805-21a890a8f04a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_sopir1']</value>
      <webElementGuid>5d7ad37e-07af-402c-b04a-c61883faaed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim via COD (Bayar Di tempat)'])[1]/following::select[1]</value>
      <webElementGuid>aa317487-73aa-454e-86f1-be79fac949ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarii Sentral Java'])[2]/following::select[1]</value>
      <webElementGuid>7ba3a3b2-ac3e-41e3-8523-45e4a59c38e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COD - Padang Lua'])[1]/preceding::select[2]</value>
      <webElementGuid>387923e4-d4bd-4711-b8c2-ab92f6614235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/select</value>
      <webElementGuid>62bdf6b4-713d-4f5f-80bc-9423f08644ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kode_sopir1' and @id = 'list_sopir1' and (text() = '
                                              - Kirim via Kurir Lokal -Roda 2Roda 4' or . = '
                                              - Kirim via Kurir Lokal -Roda 2Roda 4')]</value>
      <webElementGuid>1614bb58-6b70-4886-92de-c6c83840a765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
