<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose files_uploadFile</name>
   <tag></tag>
   <elementGuidId>dcb5ec3f-1386-4748-8c57-27f6648b8e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ajax-upload-id-1694164887592</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ajax-upload-id-1694164887592']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc30d377-1fa1-4245-9640-b5ec7aca0209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>47b043d4-a5e7-4bcf-8109-f6a21244b640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ajax-upload-id-1694164887592</value>
      <webElementGuid>604f389a-ca01-435d-aa16-b77e6dbdb19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uploadFile[]</value>
      <webElementGuid>a5da0402-4055-4de7-8068-bf05a9975766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajax-upload-id-1694164887592&quot;)</value>
      <webElementGuid>c39e2725-9aa0-43e9-a638-465dc37d4667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ajax-upload-id-1694164887592']</value>
      <webElementGuid>57a0bb35-218b-498b-bdf2-d47616cb93c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/form/input</value>
      <webElementGuid>41b8fb21-4d1e-4eb9-aa96-0520d2070169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ajax-upload-id-1694164887592' and @name = 'uploadFile[]']</value>
      <webElementGuid>87fc6d05-6990-4c81-9929-39b840ad0c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
