<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BAYAR SEKARANG</name>
   <tag></tag>
   <elementGuidId>23d8f441-ac3c-4cf2-a0b6-d250d300ec76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75375cf4-d3e7-4b84-a13b-58a88ea5a2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e5a27dec-be96-4451-919c-20dcc8ea97ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-block</value>
      <webElementGuid>eaf42833-62dd-42aa-a17e-111b35af602b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BAYAR SEKARANG</value>
      <webElementGuid>4595c86f-dcff-48ca-83fa-e61e72331950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cVa&quot;)/div[@class=&quot;card-body&quot;]/form[@id=&quot;form&quot;]/button[@class=&quot;btn btn-success btn-block&quot;]</value>
      <webElementGuid>796b283f-7ed9-4739-98fc-5cc89a1ba3d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2a04e674-1141-4e30-bbd8-6fdff497495c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/button</value>
      <webElementGuid>4df6ec58-c0a5-4cb6-aeeb-68d57429da61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Setor tunai sangat TIDAK DISARANKAN'])[1]/following::button[1]</value>
      <webElementGuid>7cc58ac2-c470-46ce-8490-751ddceedd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya setuju dengan syarat &amp; ketentuan diatas'])[1]/following::button[1]</value>
      <webElementGuid>6f0a83c8-4bc4-4285-a7fc-502c7df8ab7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QRIS'])[1]/preceding::button[1]</value>
      <webElementGuid>fe510b46-b386-44b9-bc69-ab5e0cefb2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[2]/preceding::button[1]</value>
      <webElementGuid>8bfd9fab-c9f4-4ae7-bbdf-239869361fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BAYAR SEKARANG']/parent::*</value>
      <webElementGuid>b4baaf59-c643-45b9-a657-02554fa7ee9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>17bc5638-7291-43c8-977d-5d55f6fc22d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'BAYAR SEKARANG' or . = 'BAYAR SEKARANG')]</value>
      <webElementGuid>e1ea36d1-eae5-4aed-a03d-c5d85f493d19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
