<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Anda bersedia menggunakan email untuk mendaftar akun iPaymu_check_register_ipaymu</name>
   <tag></tag>
   <elementGuidId>3ee14a3e-eeb1-4ac5-9e27-96421f1f1660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkVa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkVa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>628267e0-ad08-49e2-b546-5ff3b668d1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>6f342c37-5e13-4f81-9223-238ce3c0dbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_register_ipaymu</value>
      <webElementGuid>405924f6-c72e-4f54-924f-f65aa1d06726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a9dc8827-7f3d-45b0-be52-cef4e9863219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>add80233-8c34-4554-bf12-c65abc5cdd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkVa</value>
      <webElementGuid>9378e037-ec11-41ea-9a66-3e5fa114f92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkVa&quot;)</value>
      <webElementGuid>57eadbe6-7bae-4f65-8af2-da4efa4fa715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkVa']</value>
      <webElementGuid>7744a035-6811-4ad9-bbb8-cb5981360e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div/div/div[2]/input</value>
      <webElementGuid>104af180-c524-4bbf-9e26-52c37ad2e110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>13332420-4555-49af-80be-ade720a7889c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'check_register_ipaymu' and @type = 'checkbox' and @id = 'checkVa']</value>
      <webElementGuid>527ad737-e9d8-41f6-b420-1f3a03d7fa97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
