<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pembayaran melalui_type</name>
   <tag></tag>
   <elementGuidId>b6db9f32-c94f-4603-83a7-d868c5a1de3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permatava</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='permatava']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eec923f2-24d9-471c-a0a1-86c0e8a7b53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permatava</value>
      <webElementGuid>33dedda4-5bc3-40f4-8f08-4f81900c0f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1db0beff-47fa-423b-a93f-1abdbd8832a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cf8d5546-03ad-437f-b592-977c8e840814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>1e166548-ea2e-4ca0-9e74-1518ab31504a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>1f987180-f2a4-4a89-ba48-73d2f328f75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permatava&quot;)</value>
      <webElementGuid>208203cf-bd2d-4842-bcfc-96f744786138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='permatava']</value>
      <webElementGuid>5a052d8a-84b1-4c3b-9a9c-f16ec06861c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[9]/div/input</value>
      <webElementGuid>6dcfc708-7b05-4efb-88c9-25cedcd81266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>380f56df-7c34-494b-bc62-6c8f9639f6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'permatava' and @type = 'radio' and @name = 'type']</value>
      <webElementGuid>d0105fef-4f33-474c-bcac-3ef48f80ba5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
