<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dikirim</name>
   <tag></tag>
   <elementGuidId>ae7ddea3-e328-445f-bf90-79c8b6c3ffad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Dikirim?')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f4e6746-9cf2-4017-b1ad-85fca8ffd18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Yakin Ubah status pesanan jadi Dikirim?')</value>
      <webElementGuid>c53c0d9b-9fbc-49c2-92b9-fd1a0b8908c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=179&amp;status=3</value>
      <webElementGuid>a53f04b4-d859-4c28-af4b-6ee521f994c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dikirim</value>
      <webElementGuid>db040ecc-609d-44da-87c1-fcbb8b542702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/center[1]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>94b6ab37-9b12-4852-aca2-b1829349e5e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Dikirim?')&quot;]</value>
      <webElementGuid>bc0aa73c-830d-46ce-91ab-1cf9dede0f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[8]/center/div/ul/li[4]/a</value>
      <webElementGuid>83861aea-2c61-476a-b34e-6e24046b249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dikirim')]</value>
      <webElementGuid>fa1ee390-613d-49ab-8a6a-b1b564ca3c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi'])[2]/following::a[1]</value>
      <webElementGuid>c1952eae-29ef-4593-8b35-79c7fbf9b8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[1]/following::a[2]</value>
      <webElementGuid>550c7575-5459-4c36-8ac9-fe451224161f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[1]/preceding::a[1]</value>
      <webElementGuid>389e1d92-b9a6-45da-9a61-cd2b5cdb78c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal/Hapus'])[1]/preceding::a[2]</value>
      <webElementGuid>b193d8f3-a5d9-4e35-aeb9-260c71272ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dikirim']/parent::*</value>
      <webElementGuid>a7c02508-164f-4222-b142-7b97f33c8e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=179&amp;status=3')]</value>
      <webElementGuid>9d1a566c-a23d-4f0a-838b-d17a244f66cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>ee879e0d-c6a6-4501-9aca-a20171a51065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=179&amp;status=3' and (text() = 'Dikirim' or . = 'Dikirim')]</value>
      <webElementGuid>d88eab0a-88eb-49d5-b60f-6220242d6722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
