<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ukuran_variasi201</name>
   <tag></tag>
   <elementGuidId>07fa65fa-d460-4d16-9738-f9cd33aa2295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;variasi201&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='variasi201']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eb2d3c0-1ac0-4d1e-bb0e-adc278bd8161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b627b49-8cf9-4542-8b8b-2e36e485210d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>variasi201|Ukuran:Menengah</value>
      <webElementGuid>f2184171-8b13-4f08-b13b-f82ebc36eb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>variasi201</value>
      <webElementGuid>26717b46-e4c7-43a6-80fa-1d736f3d4503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-section--shopping ps-shopping-cart&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ps-section__content&quot;]/div[@class=&quot;table-responsive&quot;]/div[@class=&quot;keranjang-all&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12&quot;]/form[1]/div[@class=&quot;show_cart_detail&quot;]/div[@class=&quot;ps-product--cart-mobile&quot;]/div[@class=&quot;ps-product__content&quot;]/div[1]/div[2]/input[1]</value>
      <webElementGuid>8ae8fbaa-5e00-483a-8acc-779c5bbd4a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='variasi201']</value>
      <webElementGuid>00e307b5-a162-478d-81c7-fec46fed3461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>609b4c90-fd96-4a3b-a0b5-0ff6b63904af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'variasi201']</value>
      <webElementGuid>87525318-1de7-4f94-9d92-6fb846e5ac6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
