<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proses</name>
   <tag></tag>
   <elementGuidId>0e6bff73-dc67-41fb-87cb-3f6d0e54dbe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr[2]/td[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>389aa322-7b3a-4501-8053-ddd913925937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>cf9a840b-a48e-4408-83a6-ff0a62c9c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proses</value>
      <webElementGuid>cacfcc75-dcee-47a3-91fb-a7093273e85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[5]/span[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>ac7d57e8-cad3-41f2-8497-764a070112bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr[2]/td[5]/span</value>
      <webElementGuid>2dbeeb64-b92d-44f3-ba54-61054b11e7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOPIR - Vixion R'])[1]/following::span[1]</value>
      <webElementGuid>9d7eb413-566c-4a5e-a77a-4feb18053e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='irfan.afandi'])[1]/following::span[1]</value>
      <webElementGuid>76c06c2d-9182-4ed0-9014-7a94a5cd6a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 6,299 (1 Produk)'])[1]/preceding::span[1]</value>
      <webElementGuid>51aa0f0e-91e1-4cae-8929-9eef72e721fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[3]/preceding::span[2]</value>
      <webElementGuid>eacc87a7-2fc4-4060-a477-e7cf9627ef38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/span</value>
      <webElementGuid>2dae9c00-c08f-4cf6-8ebb-cd87a5807091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Proses' or . = 'Proses')]</value>
      <webElementGuid>5837eb63-ed16-46d4-9b81-d3a595d0c317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
