<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selesai</name>
   <tag></tag>
   <elementGuidId>dca96de5-6864-4da4-9c6d-df03482c1a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr/td[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3507261b-b0e0-4b54-9fb7-c350bb47d3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>7faa9f7a-e1b3-42e9-9325-e78082406335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>81a8c64a-b83c-48bb-947a-bd0f8a43affc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]/span[@class=&quot;text-success&quot;]</value>
      <webElementGuid>1ae5816b-a5f4-4775-ad27-88b806ed1dd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[5]/span</value>
      <webElementGuid>dc24cec3-2bcc-4f21-a57d-92120bf80338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOPIR - Vixion R'])[1]/following::span[1]</value>
      <webElementGuid>d2152230-87ba-464e-8f35-0ac3c03c2ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='irfan.afandi'])[1]/following::span[1]</value>
      <webElementGuid>0098bc5c-1082-4090-905f-e02bcc38d5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 6,299 (1 Produk)'])[1]/preceding::span[1]</value>
      <webElementGuid>c1958113-4090-4df5-bf26-fcdbbf33283c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/preceding::span[2]</value>
      <webElementGuid>a16fa031-dd81-4316-8524-1c6d3b6116dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>ec2a914c-4f82-4e79-8f15-434c75f0b2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span</value>
      <webElementGuid>f9d76122-cb95-4b88-a164-b19f20b6528a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>94b26c0a-a0f3-46f9-9f65-5e5c05e3ae99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
