<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total TagihanTransfer_b</name>
   <tag></tag>
   <elementGuidId>f8de564d-4aed-4674-bfd7-cdddfe43c239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.ps-form--order-tracking > div.form-group > input[name=&quot;b&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='b'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fec8010a-abc8-4104-a804-6bd69e52ec01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87349171-d938-4c9c-8b3e-89dae9f34f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>34999fe6-57fb-4c42-8eb2-f454ac2616cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control font-weight-bold text-success</value>
      <webElementGuid>1295bca7-39ec-4e52-b02a-3004b315c32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8,027</value>
      <webElementGuid>218fc07f-0924-478c-a03f-c2704cbfeb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-order-tracking&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ps-section__content&quot;]/form[@class=&quot;ps-form--order-tracking&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control font-weight-bold text-success&quot;]</value>
      <webElementGuid>756ec850-c69a-4935-853e-326225357447</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='b'])[3]</value>
      <webElementGuid>e278fdf3-95eb-461c-8480-e119d3696a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/form/div/input</value>
      <webElementGuid>6335790d-53ea-42c4-a75c-4b39183879b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'b']</value>
      <webElementGuid>37384cec-3176-4853-b060-a1753633fc4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
