<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose files_uploadFile</name>
   <tag></tag>
   <elementGuidId>68e6ebd1-83c1-4f62-afe8-1fe333cc7c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ajax-upload-id-1695781269517</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ajax-upload-id-1695781269517']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5527efc9-2744-4dd4-b76b-cb29d2eb0ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>27ed00ae-9d88-479c-8ce6-7fb5da86fd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ajax-upload-id-1695781269517</value>
      <webElementGuid>3c3c1bd4-d611-4b03-977c-2dedb434c1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uploadFile[]</value>
      <webElementGuid>c035d74a-3413-43d2-b26a-51a30ead762a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajax-upload-id-1695781269517&quot;)</value>
      <webElementGuid>de353d0c-a5bc-4728-bd17-247678e2b1d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ajax-upload-id-1695781269517']</value>
      <webElementGuid>be574587-2d64-4a02-a755-abc8218c8e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/form/input</value>
      <webElementGuid>cd637565-7ba1-42ec-a26e-ddb65ab269c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ajax-upload-id-1695781269517' and @name = 'uploadFile[]']</value>
      <webElementGuid>cad2e15a-eee3-41dd-a408-c1481043499c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
