<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BAYAR SEKARANG</name>
   <tag></tag>
   <elementGuidId>9033f4ad-b301-4ffa-a518-1ca85a0f9ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qris > button.btn.btn-success.btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e596e6c8-65d8-40e4-9ba4-d24af2ae09cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3c4d530d-545c-461a-868f-bfca76c1cc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-block</value>
      <webElementGuid>f27b7a43-62a0-4eaa-b811-d8f645e9608a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BAYAR SEKARANG</value>
      <webElementGuid>44ba8e3f-b8b1-4901-a38f-b11c2f91e34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qris&quot;)/button[@class=&quot;btn btn-success btn-block&quot;]</value>
      <webElementGuid>088f44d2-2c57-47fc-926c-0b7b71639332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>3b2475d9-d148-4beb-ae9e-0fca01b77a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='qris']/button</value>
      <webElementGuid>ef8b4fd3-2d1c-405a-b52e-ab3c2d88f99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya setuju dengan syarat &amp; ketentuan diatas'])[2]/following::button[1]</value>
      <webElementGuid>6bd881fa-a5f3-4f9e-9d68-408cf135d426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda bersedia menggunakan email untuk mendaftar akun iPaymu.'])[2]/following::button[1]</value>
      <webElementGuid>887a3cba-250b-4879-945a-eebf853f7bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit Online GPN'])[1]/preceding::button[1]</value>
      <webElementGuid>cc1dbc8b-7c41-4691-af31-570175887905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[3]/preceding::button[1]</value>
      <webElementGuid>8583fe19-c9aa-4daa-a9cc-2b4e7fa484ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/form/button</value>
      <webElementGuid>cb269a6f-05fe-41d4-9d75-36161e681715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'BAYAR SEKARANG' or . = 'BAYAR SEKARANG')]</value>
      <webElementGuid>69bc40b4-d745-408c-9a6d-040eb20a6a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
