<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Keterangan Lunas</name>
   <tag></tag>
   <elementGuidId>53e8ceb6-8521-4963-8b57-9269412c0ffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(8) > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr/td[8]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88a69add-70c7-49df-83b5-423c3118d073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lunas</value>
      <webElementGuid>91c4e3ed-22ef-422f-ac84-b1ece9f0d8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/span[1]</value>
      <webElementGuid>74975b09-0161-4054-9013-dc2d0bdd57ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[8]/span</value>
      <webElementGuid>63760669-0b72-456e-803c-277e97d087be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank BRI Syariah'])[1]/following::span[1]</value>
      <webElementGuid>d4f9675a-1ccb-413b-a34d-cf167da416a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='irfan.afandi'])[1]/following::span[1]</value>
      <webElementGuid>8ce50b5b-c79e-48ed-8ef9-f651dfabca3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 16 total entries)'])[1]/preceding::span[3]</value>
      <webElementGuid>075b9636-bd39-4216-bfa4-db3ecd26006f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lunas']/parent::*</value>
      <webElementGuid>391d075b-5674-4fe1-9871-06a57d45f9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/span</value>
      <webElementGuid>10f98e7c-0d24-43ff-a471-7b8f723c6e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lunas' or . = 'Lunas')]</value>
      <webElementGuid>96a88425-5def-42b8-acb5-a08bb6e586ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
