<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menunggu Pembayaran</name>
   <tag></tag>
   <elementGuidId>45100147-2f63-421f-8a35-b1702a9a21ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pending-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pending-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d198049f-2f87-4a53-8b3b-b15c58401a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>5790473f-5c57-4b2c-b1c4-6221de7fabab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pending-tab</value>
      <webElementGuid>7ca8d3c6-ef38-479b-88e0-a9c39fdff5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>faf8c017-54f9-4524-b60c-75f36b2f9168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pending</value>
      <webElementGuid>5f5fe509-27d8-456e-9c63-0ee0035c077b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>82796769-0e31-4c59-9e98-69eef216a6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pending</value>
      <webElementGuid>9242bb61-5fce-4d4d-8bde-c01c8c80cc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eeb6f5b8-44c5-4e59-a7e9-cd03d8f79325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menunggu Pembayaran 0</value>
      <webElementGuid>9ae24022-4120-40ba-a008-e49906866933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pending-tab&quot;)</value>
      <webElementGuid>5249b40b-6145-4283-a3a3-af3f5162d96c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pending-tab']</value>
      <webElementGuid>e7bbf803-1b22-47f5-a207-d40eb1c749ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li/a</value>
      <webElementGuid>0376bac5-d10b-4e74-a492-71b60f87d92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 74,394'])[1]/following::a[1]</value>
      <webElementGuid>030096f6-42b2-4b6c-91c6-ff5505a26556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menunggu Pembayaran']/parent::*</value>
      <webElementGuid>8fdf7d3a-28b2-4539-934a-e814e1d8177d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pending')]</value>
      <webElementGuid>c9e0d09e-8bf9-46e7-bfcd-538ba78c9098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div[2]/ul/li/a</value>
      <webElementGuid>a0ccd868-3103-454a-871b-869f16889a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pending-tab' and @href = '#pending' and (text() = 'Menunggu Pembayaran 0' or . = 'Menunggu Pembayaran 0')]</value>
      <webElementGuid>24bf727d-903a-41b4-adbd-3f440937401d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
