<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pesanan Diproses</name>
   <tag></tag>
   <elementGuidId>2ec5a752-4215-4765-b81a-8a51a401abad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proses-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='proses-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18dcf99d-c4d3-4c96-93b8-c7227f20e628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active show</value>
      <webElementGuid>e40ebae3-35c4-4cf0-a08a-81ce15bf240e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proses-tab</value>
      <webElementGuid>2467cc02-b0e6-4244-8850-cf15d041d63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5cc91678-0b52-4f43-9f8f-0911e2d60716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#proses</value>
      <webElementGuid>f2b60bc7-014f-4027-8bb0-e7813e8df485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5f627a9d-4b9c-4c61-9dd8-66323d921b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>proses</value>
      <webElementGuid>eb68aefd-fba3-4bad-ba84-59e057466484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7f11c9a-ca85-4d4f-a642-5dd6a7b0c571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesanan Diproses 0</value>
      <webElementGuid>d5c79bc0-7a0e-4bab-b0df-f37af09a25fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proses-tab&quot;)</value>
      <webElementGuid>d6a74ff2-0191-41d1-ac7f-ec9d98221c3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='proses-tab']</value>
      <webElementGuid>554f0033-75ca-4b93-8d18-28c7e39e23d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[2]/a</value>
      <webElementGuid>cc2c50c3-77a9-412c-a580-52682673eb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 74,394'])[1]/following::a[2]</value>
      <webElementGuid>402ac6b2-d565-48e7-ad2f-f67aa8e66262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesanan Diproses']/parent::*</value>
      <webElementGuid>04697486-b22c-4211-8d72-201d8886138d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#proses')]</value>
      <webElementGuid>32018ed3-036f-425b-93f1-0c638ef436e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>bda4b0ac-cafd-4c5b-9b6b-d9f152681c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'proses-tab' and @href = '#proses' and (text() = 'Pesanan Diproses 0' or . = 'Pesanan Diproses 0')]</value>
      <webElementGuid>751a6092-be9c-4d40-80fc-3d068e72c3d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
