<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sampai Tujuan</name>
   <tag></tag>
   <elementGuidId>8b3fff83-6893-492e-bf4b-cc6e7afe08a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selesai-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='selesai-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4af8fb8-775f-4bf7-9d0e-bef78bfeda0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active show</value>
      <webElementGuid>7c180c99-61cc-4136-8f0e-ee1bda436937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selesai-tab</value>
      <webElementGuid>869a8d01-6631-4353-9fdc-2a1ba60ac34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>cced3144-e21d-4829-9e8a-acec6adff6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#selesai</value>
      <webElementGuid>609aaf8e-7ca6-476c-937d-94a8042c613a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c1d7154e-3241-4b86-bbfa-c57d98606ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>selesai</value>
      <webElementGuid>6f52076d-99ba-4668-b2d4-4b69a5f07b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>863adfca-4fbd-47cc-85d1-a3c9320b054b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sampai Tujuan 0</value>
      <webElementGuid>bf6f9347-5330-4890-af2d-94b7f9c7177b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selesai-tab&quot;)</value>
      <webElementGuid>b6d331c1-8e6d-4119-ae38-2b6fdc4982b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='selesai-tab']</value>
      <webElementGuid>6d6a19d1-2318-449a-9c0f-fb4921165a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[4]/a</value>
      <webElementGuid>183c1e64-5bb3-455c-b381-962fb6ce6e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFORMASI'])[1]/preceding::a[1]</value>
      <webElementGuid>d0a751a4-c499-437f-843a-a82870591351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='disini'])[1]/preceding::a[1]</value>
      <webElementGuid>3b0c4c4b-7edb-49e5-a42a-a312df72e503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sampai Tujuan']/parent::*</value>
      <webElementGuid>8d78a7a2-3e96-412f-bf6b-0d90aff0dec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#selesai')]</value>
      <webElementGuid>37bd40cd-2285-49df-ad99-31f08ce10242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>77886659-8e03-4f6d-8a6a-6f903b8a6f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'selesai-tab' and @href = '#selesai' and (text() = 'Sampai Tujuan 0' or . = 'Sampai Tujuan 0')]</value>
      <webElementGuid>d6d92827-3a0f-4ea2-b12e-3e3b927baefd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
