<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status Selesai di user</name>
   <tag></tag>
   <elementGuidId>bad0589d-c929-4375-8067-4c1617ee10c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-10 > span.text-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selesai']/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42e2b1a6-2f2a-4275-bcd9-c64d85b1bb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>6bc87962-60f2-487e-b0ab-2c79f44c17de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>3c360ce0-6f62-4f9f-a2d6-a5e6995c3624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selesai&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-10&quot;]/span[@class=&quot;text-success&quot;]</value>
      <webElementGuid>240e0a81-78ee-4a27-912a-aba3eebabf9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selesai']/div[3]/div/span</value>
      <webElementGuid>7b632a9d-da04-4926-8533-819cc6f29940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::span[1]</value>
      <webElementGuid>697d16c0-0731-4688-b4c9-d021f7666940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarii Sentral Java'])[1]/following::span[1]</value>
      <webElementGuid>e50af65f-452c-4c76-8829-92f0184e63dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Belanja'])[1]/preceding::span[1]</value>
      <webElementGuid>335144ef-6680-45f0-9e56-1cdefa7de388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 6,299 (1 Produk)'])[1]/preceding::span[1]</value>
      <webElementGuid>6be76836-aff8-4d22-9c0a-a40aa054442f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>a1ba9cb2-b43d-4de2-8250-e00f83222dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>3275747f-906a-4001-a6d4-a0fbb00c9037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>acdc360a-d2bf-497b-882c-886cf046334e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
