<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proses Pembayaran</name>
   <tag></tag>
   <elementGuidId>93d2ee42-2081-45ba-a128-e69523e4a283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oksimpan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='oksimpan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fee4574-dada-48d7-ba39-1aeec2e69a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e3b63f76-3d49-408c-8fb4-9fb7cb8ad932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b51c013d-8924-4146-8d3f-2ff8fe7f0e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oksimpan</value>
      <webElementGuid>02c639fc-6a54-4380-b481-ab042e0263ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-btn ps-btn--fullwidth</value>
      <webElementGuid>897a85a8-eebd-48e7-89c6-e8e762e49dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proses Pembayaran
                </value>
      <webElementGuid>5c45b384-7403-492e-bdd6-759a5c119aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oksimpan&quot;)</value>
      <webElementGuid>5f11ceee-bad2-45a2-831d-27475958c572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='oksimpan']</value>
      <webElementGuid>fafc42f2-59a3-4de0-8422-64234e7ce1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 2,799'])[1]/following::button[1]</value>
      <webElementGuid>bf540bdc-4a97-4ea5-a3b9-6741676844ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::button[1]</value>
      <webElementGuid>3f907e0b-a514-4100-b12b-20084f562a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proses Pembayaran']/parent::*</value>
      <webElementGuid>16958088-5f74-421c-bf40-4f0254b1812a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>f823fd2e-4b63-469d-a210-4b4a5d5e2c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'submit' and @id = 'oksimpan' and (text() = 'Proses Pembayaran
                ' or . = 'Proses Pembayaran
                ')]</value>
      <webElementGuid>9bf515c9-f4dc-4c3b-84dd-d7ce8443da9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
