<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kecamatan</name>
   <tag></tag>
   <elementGuidId>9df7b822-a71d-4323-8bca-0620803be68d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list_kecamatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='list_kecamatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>71064658-b966-4b2e-9f76-ea2acd039d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>cdcd5c1f-9d35-4619-83cc-a7957055f549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kecamatan</value>
      <webElementGuid>b3eaf9e6-6686-46a0-abc7-6d2b9689a361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_kecamatan</value>
      <webElementGuid>83ab9dac-fb70-407f-94c7-edd4bbbb2892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanAur Birugo Tigo BalehGuguk Panjang (Guguak Panjang)Mandiangin Koto Selayan</value>
      <webElementGuid>abbb6ba1-c451-47be-9458-50f6f7a5475e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_kecamatan&quot;)</value>
      <webElementGuid>3db0643b-57a7-48bc-9376-9e38f38a3de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_kecamatan']</value>
      <webElementGuid>279eb144-f574-4bfc-865e-e4a6fdaa1742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Kirim'])[1]/following::select[3]</value>
      <webElementGuid>35264d79-a684-48ed-bc7e-ca6bcf146038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontak'])[1]/following::select[3]</value>
      <webElementGuid>cd0668c4-22e1-4765-8e89-f032dbc85e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Produk'])[1]/preceding::select[1]</value>
      <webElementGuid>9dbfac0d-b21e-41cc-a2fc-14c8767c6385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segitiga Instan Madeira - MDB5.3 Sunset'])[4]/preceding::select[1]</value>
      <webElementGuid>e24f9ec0-d96f-4012-b2eb-d138fd42b74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>90bb90e5-ee65-4d4d-b6a8-dc97dc10bc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kecamatan' and @id = 'list_kecamatan' and (text() = 'KecamatanAur Birugo Tigo BalehGuguk Panjang (Guguak Panjang)Mandiangin Koto Selayan' or . = 'KecamatanAur Birugo Tigo BalehGuguk Panjang (Guguak Panjang)Mandiangin Koto Selayan')]</value>
      <webElementGuid>28a53830-f825-488d-9287-ed6fd2113e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
