<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Alamat Kirim_kota</name>
   <tag></tag>
   <elementGuidId>b3525657-ee11-41c6-a42c-056f05773df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list_kotakab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='list_kotakab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2be76891-56e1-4be4-a4f0-df12ee19dba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>ef23e224-4fe7-4ce3-bebe-4920056ba902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kota</value>
      <webElementGuid>63cbe2cc-3a79-4ebf-9ad9-4fc7fa176b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_kotakab</value>
      <webElementGuid>be115bab-4ec5-44c8-a857-bf811a2c6a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_kotakab&quot;)</value>
      <webElementGuid>2d0b8762-c2df-4dab-add4-d25124fb0fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_kotakab']</value>
      <webElementGuid>6bead518-6545-45dc-b5c2-c5cdbb256911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>a16071aa-5e8a-4d6f-a9b3-ee1025bb964c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kota' and @id = 'list_kotakab']</value>
      <webElementGuid>290b0312-fa8e-4ded-89c9-05dc67b6a911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
