<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button kupon</name>
   <tag></tag>
   <elementGuidId>cfe52265-c64d-48f8-a84c-1daaef388a34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit_kupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit_kupon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>adb362dd-03a8-42e3-8b2b-3ec973c73c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3691a736-2c7c-45e1-aa77-d91f8176476c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_kupon</value>
      <webElementGuid>a8c24830-69aa-46c7-bb92-9de92cebf1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-btn</value>
      <webElementGuid>762e95d8-94ec-4d6a-b722-df4ab693080f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_kupon&quot;)</value>
      <webElementGuid>f6aaf69b-2ce6-4ebe-96d8-56953554bcea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit_kupon']</value>
      <webElementGuid>fc40716e-770c-4f61-ade5-2997e646dddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1,299'])[3]/following::button[1]</value>
      <webElementGuid>1b168998-3b80-4408-a8b7-ce6d10afbe3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1,500'])[1]/following::button[1]</value>
      <webElementGuid>efd4fe68-443a-40c6-98b6-69ab3db17091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 2,799'])[1]/preceding::button[1]</value>
      <webElementGuid>45416134-80a8-4f2f-b89b-62dec652f8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>4a6b6cdd-d049-467d-b086-fef5c16fe324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submit_kupon']</value>
      <webElementGuid>b89e3ba1-6442-4744-ae64-141bd41d24cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
