<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input kupon</name>
   <tag></tag>
   <elementGuidId>622ba864-d46e-41c4-bae0-38f0a0f27ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kode_kupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kode_kupon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>708733b2-0572-49a4-aca6-4e6571662a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c509cc01-cb91-42f7-aa4f-f5ad04003686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_kupon</value>
      <webElementGuid>8f37b02c-8e9a-4ec2-858a-3447d61260fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kode_kupon</value>
      <webElementGuid>5081df6f-627d-4cb5-af0f-9ff2c221eef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7249a46-9dfe-4a0c-aa7e-241f8a2e5cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Kupon / Voucher</value>
      <webElementGuid>05e8f170-38a9-479f-aa93-e34e5ad26dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kode_kupon&quot;)</value>
      <webElementGuid>cdbe18e1-37d9-4987-9295-322160c92aa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kode_kupon']</value>
      <webElementGuid>59672f07-79c4-4729-a34d-869fc9658555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>546c6f93-f475-4fa3-acd0-5cc9583c5bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kode_kupon' and @id = 'kode_kupon' and @type = 'text' and @placeholder = 'Kode Kupon / Voucher']</value>
      <webElementGuid>9169c834-e050-471d-ad50-48a77d9e0bd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
