<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus Barang</name>
   <tag></tag>
   <elementGuidId>e37be468-c98d-4d14-9100-d6f1162cf724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>056a897e-6f7c-4f23-961d-25d0fede4855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31a41ed2-4298-4d41-95c1-67d6cc7c63b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_delete</value>
      <webElementGuid>f52485a3-60d7-4f92-a671-23c42ec13685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-btn</value>
      <webElementGuid>783ada1a-3400-418b-a4db-f3063c0061eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus Barang</value>
      <webElementGuid>44349121-30d2-4a09-99ab-0f3361d9814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_delete&quot;)</value>
      <webElementGuid>24bddb30-a88d-48d6-ae46-36c8626b39e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_delete']</value>
      <webElementGuid>6c6f492d-bc6f-4987-a975-a15f83304994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal_Delete']/div/div/div/center/div/button[2]</value>
      <webElementGuid>76a36f50-bf32-4267-8b05-62d3da94de17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>f3c0920e-7bb1-44c3-8510-7afe9f9d1034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Barang ?'])[1]/following::button[2]</value>
      <webElementGuid>b4a5a94a-d5c1-46e2-9157-7fa6e34abe98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Notifikasi'])[1]/preceding::button[1]</value>
      <webElementGuid>4e18da85-5590-4da5-a464-5096adbc7c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[2]/preceding::button[1]</value>
      <webElementGuid>5d0d5f6c-14ef-4b75-a5b9-d657b242f110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hapus Barang']/parent::*</value>
      <webElementGuid>40c9947e-2948-4fb5-ad8e-72ad602e1198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>83087b3e-7cdb-4bc7-b54b-9305cf6245f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_delete' and (text() = 'Hapus Barang' or . = 'Hapus Barang')]</value>
      <webElementGuid>b263a65b-3892-4d06-8cca-c3b4f61625e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
