<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>biaya proteksi Rp. 2.500</name>
   <tag></tag>
   <elementGuidId>da3e7be6-ecfc-40ac-a82f-2e6c7ffea75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insurance-amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='insurance-amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa8ce76b-51d8-419f-841c-8798b154ee61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insurance-amount</value>
      <webElementGuid>c585f6dd-c657-4b7c-bb8a-f4338becc47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp. 2.500</value>
      <webElementGuid>10e5efed-4c01-4478-a49b-e6ab44363650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-amount&quot;)</value>
      <webElementGuid>cb2a1d67-b278-42d9-853e-a23c59e5acd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='insurance-amount']</value>
      <webElementGuid>c8eb277d-ddbd-4e5a-9342-bd1971716395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='cInsurance']/span[2]</value>
      <webElementGuid>9009a84f-fbfd-4234-a258-f3d8e674d5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya Proteksi'])[1]/following::span[1]</value>
      <webElementGuid>9301e8c7-8acd-4c0f-b660-ed3b28029b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp.'])[8]/following::span[5]</value>
      <webElementGuid>a9489237-0c07-47a4-a88d-75262313722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Rp. 2.500'])[1]/preceding::span[1]</value>
      <webElementGuid>ecf7ee31-386d-4b7e-8bf0-28d910d520c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2.500']/parent::*</value>
      <webElementGuid>932238d8-6ca6-4b8a-8453-d809eed61d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/span[2]</value>
      <webElementGuid>a66ebebd-569f-414d-b709-17ce9ac2eb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'insurance-amount' and (text() = 'Rp. 2.500' or . = 'Rp. 2.500')]</value>
      <webElementGuid>bd199bb3-da21-4c93-aa51-2ede36749aaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
