<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Biaya Proteksi_insuranceCheck</name>
   <tag></tag>
   <elementGuidId>06806d1d-0ab1-41b2-8829-cfe94c1d73fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insuranceCheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;insuranceCheck&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b20da2bc-8379-4486-bd20-48b652a0aa0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f505bb61-3e24-49ca-b9d0-6b63f25418de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>24f01349-959e-4325-a695-7d93f0cbb3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9483294a-e525-4bc1-b792-013a9d04d20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insuranceCheck</value>
      <webElementGuid>f493024c-4521-432c-9a13-43fcdf2d1de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>insuranceActivate()</value>
      <webElementGuid>b3b7d1da-2a82-4094-86d9-983046adf2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insuranceCheck&quot;)</value>
      <webElementGuid>75bddb38-2318-4da9-a779-55ee23a45445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='insuranceCheck']</value>
      <webElementGuid>a3200220-50ec-4b8b-af6b-a061ce9fde9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product']/div/div[3]/div/input</value>
      <webElementGuid>47af52c3-ed4f-42a8-bccd-460929293af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>59ff44d6-30d0-4c46-8220-7faf0f0ce52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'insuranceCheck']</value>
      <webElementGuid>0732d637-8bf7-428c-ada1-8cb505efeeb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
