<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Anda bersedia menggunakan email untuk mendaftar akun iPaymu_check_register_ipaymu</name>
   <tag></tag>
   <elementGuidId>cbb155dd-1362-4f0c-ade7-3683f4a83d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkQris</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkQris']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a89967d7-c1ea-4410-b786-c263a301c4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b9455562-5992-4023-92cd-09583140b2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_register_ipaymu</value>
      <webElementGuid>1227c1b7-8a0c-47d9-951b-46113590a5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6322fa83-5e66-4759-a37f-f426002ed0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6cb53405-6319-4bbb-b128-e43fe11ad27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkQris</value>
      <webElementGuid>dc4e239c-1e6a-41d1-9133-7ce69ad7a681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkQris&quot;)</value>
      <webElementGuid>d988eb11-24e3-4ef6-ab4e-3f15ee26a6c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkQris']</value>
      <webElementGuid>c6f0d636-0d8a-4f45-812b-41b4b4ca3660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='qris']/div[4]/div/div/div[2]/input</value>
      <webElementGuid>c7800ece-69e9-472a-8530-c2c93e316256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>8d122d39-cc08-40e4-b121-c53f30f61d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'check_register_ipaymu' and @type = 'checkbox' and @id = 'checkQris']</value>
      <webElementGuid>e0d21a08-0c85-44ca-910e-3297d9ae873c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
