<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ipaymu</name>
   <tag></tag>
   <elementGuidId>17dcb071-347d-4e0e-813b-19e42acdc57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.footer-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='iPaymu Logo White']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6af7e8c3-93ce-488b-b671-d5a0d3bab295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/asset/images/logo-white.png</value>
      <webElementGuid>792b6a11-edf8-4c1c-a58a-6c9abc287eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-logo</value>
      <webElementGuid>a0b2bf8f-e061-48d4-b3fb-4544884fe7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>iPaymu Logo White</value>
      <webElementGuid>659c1449-cf11-4258-a7f3-acc46d5cea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row-logo&quot;]/img[@class=&quot;footer-logo&quot;]</value>
      <webElementGuid>4bbbd903-0748-4e12-ae0c-32fded380fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='iPaymu Logo White']</value>
      <webElementGuid>01df31a0-eaa6-41fc-a6c6-15de1a904c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>5ff9f061-e636-4394-9303-a8e53834bd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/asset/images/logo-white.png' and @alt = 'iPaymu Logo White']</value>
      <webElementGuid>d692fe75-6948-4e58-a4d3-0ccd578f1d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
