<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PHPMU.COM</name>
   <tag></tag>
   <elementGuidId>1ed2ac18-e9cf-48c9-8f53-86e2028d961a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '
                    PHPMU.COM
                ' or . = '
                    PHPMU.COM
                ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.pay-to</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[2]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5f2565c8-7da0-43be-b056-40ea0c0a6380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pay-to</value>
      <webElementGuid>f286ddcc-ede4-49b7-99c9-ff0d103fad82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    PHPMU.COM
                </value>
      <webElementGuid>2b20565c-cb11-4423-9131-53d9d4197ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mb-5&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-8 d-none d-lg-block d-md-block&quot;]/h4[@class=&quot;pay-to&quot;]</value>
      <webElementGuid>368d945c-8035-4d95-a813-d6c7628aa3b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHPMU.COM'])[1]/following::h4[1]</value>
      <webElementGuid>efc5a7da-533b-4b8e-95f1-493a86298b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/preceding::h4[1]</value>
      <webElementGuid>5447b1f7-1644-473d-9f59-ff6fec8abca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 13.799'])[1]/preceding::h4[1]</value>
      <webElementGuid>fbfdb033-fec7-4586-864b-a6870fd6116e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>e3d573b1-489e-4fb5-a73b-e5226c160e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '
                    PHPMU.COM
                ' or . = '
                    PHPMU.COM
                ')]</value>
      <webElementGuid>f74b02e9-1e77-449d-be6e-76d16d608aaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
